/mindvision_camera:
    ros__parameters:
        camera_name: 'mv_camera'
        sn: '048021610077'
        camera_k: [1552.7, 0.0, 640.0, 0.0, 1537.9, 360.0, 0.0, 0.0, 1.0]
        camera_d: [0.0, 0.0, 0.0, 0.0, 0.0]
        fps: 100
        custom_qos: false
        auto_exposure: 0
        exposure: 3000
        saturation: 0