/**:
    ros__parameters:
        serial_name: '/dev/ttySerial'
        serial_send: True
        serial_recv: True
        serial_bps: 1152000
        debug: True
        custom_qos: True
        imu_name: 'imu/data_raw'
        gimbal_cmd_name: 'cmd_gimbal'
        shoot_speed_name: 'shoot_speed'
        set_mode_name: ['auto_aim','nahsor']