##若未设置udev权限，则需要进入root用户才能启动相机结点（除虚拟相机外）
infantry4/mindvision_camera:
    ros__parameters:
        camera_name: 'mv_camera'
        sn: '048021610074'
        config_path: './master-base/rm_entity_cam/config/048021610074.Config'
        camera_info_url: 'package://rm_entity_cam/config/048021610074.yaml'
        fps: 200
        best_effort_qos: true


daheng_camera:
    ros__parameters:
        camera_name: 'daheng_camera'
        sn: 'KN0210040023'
        config_path: './master-base/rm_entity_cam/config/daheng_cam_config.txt'
        camera_info_url: 'package://rm_entity_cam/config/KN0210040023.yaml'
        lut_detail: [0., 2., 0.] # (!必须使用小数形式)对比度调节参数[-50-100] 伽马调节参数[0.1-10] 亮度调节参数[-150-150]
        fps: 200
        best_effort_qos: false